AY2425S1-CS2113-W14-4/tp

- docs/AboutUs.md
Step 5. PR to team repo master branch
> Commit and Push

- src/main/java/seedu/duke/Command/Command.java
Closes #21, creating basic abstract class Command. Parameters of execute() method should be updated when classes such as TaskList and Storage are created.
> Create abstract class Command

- src/main/java/seedu/pill/Pill.java
- src/main/java/seedu/pill/command/Command.java
- src/main/java/seedu/pill/exceptions/ExceptionMessages.java
- src/main/java/seedu/pill/exceptions/PillException.java
- src/main/java/seedu/pill/util/Parser.java
- src/main/java/seedu/pill/util/Printer.java
- User Interface
- Create Parser Class
- Add Custom Exceptions
- Add Error Handling for Pill, Ui and Parser Classes
> Add Parser, add basic error catching

- src/main/java/seedu/pill/command/FindCommand.java
- src/main/java/seedu/pill/util/ItemList.java
- src/test/java/seedu/pill/command/FindCommandTest.java
Create FindItem command accepting itemName, overrides execute method of base class
Create findItem method given itemName, returns ListArray of matches found
Add JUnit tests for FindItem command
> Create FindItem command closes #20

- src/main/java/seedu/pill/command/HelpCommand.java
- src/main/java/seedu/pill/util/Parser.java
Help Command // initial code - attempt 03
> Help Command // initial code

- .gitignore
- src/main/java/seedu/pill/command/AddItemCommand.java
- src/main/java/seedu/pill/command/Command.java
- src/main/java/seedu/pill/command/DeleteItemCommand.java
- src/main/java/seedu/pill/command/EditItemCommand.java
- src/main/java/seedu/pill/command/FindCommand.java
- src/main/java/seedu/pill/command/HelpCommand.java
- src/main/java/seedu/pill/command/ListCommand.java
- src/main/java/seedu/pill/exceptions/ExceptionMessages.java
- src/main/java/seedu/pill/util/ItemList.java
- src/main/java/seedu/pill/util/Parser.java
- src/main/java/seedu/pill/util/Storage.java
- src/test/java/seedu/pill/command/FindCommandTest.java
- src/test/java/seedu/pill/command/ListCommandTest.java
Closes #31, Closes #35
Create a basic Storage class that saves to file after every command that edits the list. Updated the Command class and all inherited subclasses to take in Storage class as part of the execute function. Also accordingly updated existing JUnit tests such that they did not break.
> Create Storage class

- src/main/java/seedu/pill/command/HelpCommand.java
Help Command // updated
Notes:
Revised to reflect changes in code from Storage class implementation.
> Help Command // updated

- src/main/java/seedu/pill/Pill.java
- src/main/java/seedu/pill/command/FindCommand.java
- src/main/java/seedu/pill/exceptions/ExceptionMessages.java
- src/main/java/seedu/pill/util/Parser.java
- src/main/java/seedu/pill/util/Ui.java
> Add ItemList instantiation into Parser and Ui

- docs/UserGuide.md
> User Guide V1.0

- src/main/java/seedu/pill/command/HelpCommand.java
Help Command // improved 'help' and error messages
Notes:
- Displays better example usage for every command.
- Added 'edit' command.
> Help Command // improved 'help' and error messages

- src/main/java/seedu/pill/Pill.java
- src/main/java/seedu/pill/exceptions/ExceptionMessages.java
- src/main/java/seedu/pill/util/Item.java
- src/main/java/seedu/pill/util/ItemList.java
- src/main/java/seedu/pill/util/Storage.java
- src/test/java/seedu/pill/util/LoadDataTest.java
Create methods to load data
Define relevant exception messages
Create ItemList constructor that receives an ArrayList of items
Define Item equality
Write JUnit tests for data loading
> Implement data loading from local file

- src/main/java/seedu/pill/command/HelpCommand.java
- src/main/java/seedu/pill/util/Parser.java
> Bug Fixes for Help Command: Logging and Parser Corrections

- src/main/java/seedu/pill/Pill.java
- src/main/java/seedu/pill/util/Parser.java
Log chat conversation start and end
Assert quantity to be a positive integer
> Add logs and assert

- src/main/java/seedu/pill/Pill.java
- src/main/java/seedu/pill/command/AddItemCommand.java
- src/main/java/seedu/pill/command/DeleteItemCommand.java
- src/main/java/seedu/pill/command/EditItemCommand.java
- src/main/java/seedu/pill/exceptions/ExceptionMessages.java
- src/main/java/seedu/pill/util/Item.java
- src/main/java/seedu/pill/util/ItemMap.java
- src/main/java/seedu/pill/util/Parser.java
- src/main/java/seedu/pill/util/Storage.java
- src/test/java/seedu/pill/command/FindCommandTest.java
- src/test/java/seedu/pill/command/ListCommandTest.java
- src/test/java/seedu/pill/util/LoadDataTest.java
Closes #83, Closes #18
This is a massive PR since Item is deeply interwoven into how the whole system works. In short:
1. Added expiryDate parameter to Item class as an Optional<LocalDate>
2. Refactored ItemMap to accept map to a TreeSet<Item> to handle Items with different expiry dates differently, including with no expiry date
3. Refactored Parser to take in expiry date now
The above is likely massively buggy, but I realised this PR was already too big, so I'll simply raise new issues for those.
> Add expiry date element

- src/test/java/seedu/pill/command/HelpCommandTest.java
Notes:
- Added HelpCommandTest class.
- W.I.P, will add more test cases.
> HelpCommandTest // Implemented

- src/main/java/seedu/pill/util/DateTime.java
Notes:
- Added W.I.P base class for DateTime.
> DateTime // Implemented

- .gitignore
- src/main/java/seedu/pill/Pill.java
- src/main/java/seedu/pill/command/HelpCommand.java
- src/main/java/seedu/pill/util/ItemMap.java
- src/main/java/seedu/pill/util/PillLogger.java
Create PillLogger class with file and console handlers
Update logger instantiation for existing usage
> Create PillLogger class and update logger usage

- src/main/java/seedu/pill/util/Storage.java
Save expiry date to file only if present
Use get method to obtain value of optional before saving to prevent "Optional[]" formatting
> Fix parsing of optional item attribute

- docs/DeveloperGuide.md
- src/main/java/seedu/pill/Pill.java
- src/main/java/seedu/pill/command/HelpCommand.java
- src/main/java/seedu/pill/command/StockCheckCommand.java
- src/main/java/seedu/pill/exceptions/ExceptionMessages.java
- src/main/java/seedu/pill/util/ItemMap.java
- src/main/java/seedu/pill/util/Parser.java
- src/main/java/seedu/pill/util/Printer.java
- text-ui-test/EXPECTED.TXT
Closes #92 and #107
- "stock-check" command implemented. Queries the list for items that are below a certain quantity.
- Updated help command output
- Added restock reminder on startup
- fixed the following bug
> Add "stock-check" command

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/seedu/pill/exceptions/ExceptionMessages.java
- src/main/java/seedu/pill/util/ItemMap.java
- src/main/java/seedu/pill/util/Parser.java
- src/main/java/seedu/pill/util/Storage.java
- src/test/java/seedu/pill/command/AddItemCommandTest.java
1. Update on Issue #84 Handle Multi Word Input For Items
1.1 AddItemCommand parsing logic enhanced. Accepts multi words input, accepts item input ended with integer (e.g. add iPhone 16 999 2020-12-12)
1.2 DeleteItemCommand parsing logic enhanced. (Similar to 1.1)
1.3 EditItemCommand parsing logic enhanced. (Similar to 1.1)
2. JUnit Test for AddItemCommand ( Added size() and get() methods to ItemMap).
3. DG/UG update.
> #84 Handle Multi Word Input For Items and more

- src/main/java/seedu/pill/command/ExpiredCommand.java
- src/main/java/seedu/pill/util/ItemMap.java
- src/main/java/seedu/pill/util/Parser.java
- src/main/java/seedu/pill/util/Printer.java
- src/test/java/seedu/pill/util/GetExpiredItemsTest.java
Define ItemMap equality
Create method to fetch expired items from the inventory
Create method to print expired items
Add JUnit tests for getExpiredItems method
Create "expired" command to display expired items in the inventory
> Add expired items command and display on startup

- src/test/java/seedu/pill/command/HelpCommandTest.java
- src/test/java/seedu/pill/util/DateTimeTest.java
- src/test/java/seedu/pill/util/StringMatcherTest.java
**Notes:**
HelpCommandTest //
- Added more JUnit tests for better coverage.
DateTimeTest //
- Implemented JUnit test class.
StringMatcherTest //
- Implemented JUnit test class.
> JUnit Tests // Updated

- src/main/java/seedu/pill/command/HelpCommand.java
- src/test/java/seedu/pill/command/HelpCommandTest.java
**Notes:**
- Changes to add help command information for 'expired' and 'expiring' commands.
- Added JUnit test cases for further coverage.
- Added JUnit test cases to cover the new help commands.
> HelpCommand & HelpCommandTest // Updated

- src/main/java/seedu/pill/command/HelpCommand.java
- src/main/java/seedu/pill/util/DateTime.java
- src/main/java/seedu/pill/util/Order.java
- src/main/java/seedu/pill/util/OrderItem.java
- src/main/java/seedu/pill/util/StringMatcher.java
- src/main/java/seedu/pill/util/Transaction.java
- src/main/java/seedu/pill/util/TransactionManager.java
**Notes:**
- Added Transaction class.
- Added TransactionManager class.
- Added Order class.
- Added OrderItem class.
- Updated HelpCommand to reflect new command functions.
> New Classes & Updated Classes

- src/test/java/seedu/pill/command/HelpCommandTest.java
- src/test/java/seedu/pill/util/OrderItemTest.java
- src/test/java/seedu/pill/util/OrderTest.java
- src/test/java/seedu/pill/util/TransactionManagerTest.java
- src/test/java/seedu/pill/util/TransactionTest.java
**Notes:**
- Added more tests to HelpCommandTest.java to cover new code added to HelpCommand.java
- Implemented OrderItemTest.java
- Implemented OrderTest.java
- Implemented TransactionManagerTest.java
- Implemented TransactionTest.java
> JUnit Test Classes // Implemented & Updated

- src/main/java/seedu/pill/command/UseItemCommand.java
- src/main/java/seedu/pill/exceptions/ExceptionMessages.java
- src/main/java/seedu/pill/util/ItemMap.java
- src/main/java/seedu/pill/util/Parser.java
- src/test/java/seedu/pill/command/UseItemCommandTest.java
Priority removal in this case refers to always removing items with an earlier expiry date first
> Implement Use command with priority removal

- src/main/java/seedu/pill/util/StringMatcher.java
- src/main/java/seedu/pill/util/TimestampIO.java
- src/test/java/seedu/pill/command/HelpCommandTest.java
- src/test/java/seedu/pill/util/TimestampIOTest.java
Notes:
- Added TimestampIO.java & TimestampIOTest.java
- Added further JUnit tests in HelpCommandTest.java
- Added in-line comments to StringMatcher.java for method clarity
> Timestamps, JUnit Tests, Comments // Implemented

- src/main/java/seedu/pill/Pill.java
- src/main/java/seedu/pill/command/FulfillCommand.java
- src/main/java/seedu/pill/command/OrderCommand.java
- src/main/java/seedu/pill/command/TransactionHistoryCommand.java
- src/main/java/seedu/pill/command/TransactionsCommand.java
- src/main/java/seedu/pill/command/ViewOrdersCommand.java
- src/main/java/seedu/pill/exceptions/ExceptionMessages.java
- src/main/java/seedu/pill/util/Order.java
- src/main/java/seedu/pill/util/Parser.java
- src/main/java/seedu/pill/util/TransactionManager.java
- src/test/java/seedu/pill/util/OrderTest.java
- src/test/java/seedu/pill/util/TransactionManagerTest.java
- Create commands
- Edit to use Item and ItemMap
- Create methods to list order and transaction
- Add exception messages
- Update parser
> Manage orders and transactions

- docs/team/cxc0418.md
- src/main/java/seedu/pill/command/SetCostCommand.java
- src/main/java/seedu/pill/command/SetPriceCommand.java
- src/main/java/seedu/pill/util/Item.java
- src/main/java/seedu/pill/util/Parser.java
- src/main/java/seedu/pill/util/Storage.java
Updated  the toString method to ensure all price/cost values are printed to two decimal places using %.2f.
Updated SetCostCommand, SetPriceCommand, and isANumber method to support double values and format them correctly to %.2f.
Optimized the saveItemMap method to save cost and price attributes formatted as %.2f.
Updated PPP.
> Improve cost/price command functionality

- docs/UserGuide.md
Close #193
Close #195
Close #206
Close #207
Close #210
Close #214
> Fix UG-related issues from PED
